name: CI

on:
  push:
    branches:
      - master
      - github_actions
    tags:
      - '*'
  pull_request:
    branches:
      - master
      - github_actions

env:
  UPLOAD_BUILD: true

jobs:
  PIO:
    strategy:
      fail-fast: false
      matrix:
        example:
          - "native-blink"
          - "arduino-blink"
          - "arduino-internal-libs"
          # - "examples/libopencm3-blink"
          # - "examples/libopencm3-usb-cdcacm"
          # - "examples/native-blink"
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.9]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install PIO
        run: |
          python -m pip install --upgrade pip
          pip install -U https://github.com/platformio/platformio/archive/develop.zip
          platformio platform install file://.

      - name: Build examples
        working-directory: examples
        run: |
          mkdir ${{ matrix.example }}/build_1
          pio run -d ${{ matrix.example }} >> ${{ matrix.example }}/build_1/log.txt
          cp -f ${{ matrix.example }}/.*io/build/**/*.bin  ${{ matrix.example }}/build_1/

      - name: Upload
        if: env.UPLOAD_BUILD
        uses: actions/upload-artifact@v2
        with:
          name: PIO_P29_${{ matrix.example }}
          path: examples/${{ matrix.example }}/build_1

  latest:
    strategy:
      fail-fast: false
      matrix:
        example:
          - "native-blink"
          - "arduino-blink"
          - "arduino-internal-libs"
          # - "examples/libopencm3-blink"
          # - "examples/libopencm3-usb-cdcacm"

        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.9]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install QIO
        run: |
          python -m pip install --upgrade pip
          pip install -U https://github.com/OS-Q/S03/archive/master.zip
          pio platform install file://.

      - name: Build examples
        working-directory: examples
        run: |
          mkdir ${{ matrix.example }}/build_2
          pio run -d ${{ matrix.example }} >> ${{ matrix.example }}/build_2/log.txt
          cp -f ${{ matrix.example }}/.*io/build/**/*.bin  ${{ matrix.example }}/build_2/

      - name: Upload
        if: env.UPLOAD_BUILD
        uses: actions/upload-artifact@v2
        with:
          name: QIO_P29_${{ matrix.example }}
          path: examples/${{ matrix.example }}/build_2

  release:
    strategy:
      fail-fast: false
      matrix:
        example:
          - "native-blink"
          - "arduino-blink"
          - "arduino-internal-libs"
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install QIO
        run: |
          python -m pip install --upgrade pip
          pip install -U https://github.com/OS-Q/S03/releases/latest/download/S03.zip
          pio platform install file://.

      - name: Build
        working-directory: examples
        if: matrix.os == 'ubuntu-latest'
        run: |
          mkdir ${{ matrix.example }}/build_3

      - name: Build examples
        working-directory: examples
        run: |
          pio run -d ${{ matrix.example }} >> ${{ matrix.example }}/build_3/log.txt
          cp -f ${{ matrix.example }}/.*io/build/**/*.bin  ${{ matrix.example }}/build_3/

      - name: Upload
        if: env.UPLOAD_BUILD
        uses: actions/upload-artifact@v2
        with:
          name: P29_${{ matrix.example }}
          path: examples/${{ matrix.example }}/build_3
