name: CI

on:
  push:
    branches:
      - master
      - github_actions
    tags:
      - '*'
  pull_request:
    branches:
      - master
      - github_actions

jobs:
  PIO:
    strategy:
      fail-fast: false
      matrix:
        example:
          - "examples/arduino-blink"
          - "examples/arduino-internal-libs"
          - "examples/libopencm3-blink"
          - "examples/libopencm3-usb-cdcacm"
          - "examples/native-blink"
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.9]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install PIO
        run: |
          python -m pip install --upgrade pip
          pip install -U https://github.com/platformio/platformio/archive/develop.zip
          platformio platform install file://.

      - name: Build examples
        run: |
          pio run -d ${{ matrix.example }}

  QIO:
    strategy:
      fail-fast: false
      matrix:
        example:
          - "examples/arduino-blink"
          - "examples/arduino-internal-libs"
          - "examples/libopencm3-blink"
          - "examples/libopencm3-usb-cdcacm"
          - "examples/native-blink"
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.9]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install QIO
        run: |
          python -m pip install --upgrade pip
          pip install -U https://github.com/OS-Q/S03/archive/master.zip
          pio platform install file://.

      - name: Build examples
        run: |
          pio run -d ${{ matrix.example }}
